# Generated by Django 2.1.2 on 2020-12-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='typee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='size',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='topping',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
